objects/API_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>ApiName__c</fullName>
        <label>ApiName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Value__c</fullName>
        <label>Default Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldType__c</fullName>
        <label>FieldType</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decimal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boolean</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ObjectName__c</fullName>
        <label>ObjectName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PropertyName__c</fullName>
        <label>PropertyName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ValidationMessage__c</fullName>
        <label>ValidationMessage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isRequired</label>
        <type>Checkbox</type>
    </fields>
    <label>API Configuration</label>
    <nameField>
        <label>API Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>API Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/FieldValidation__c.object
<CustomObject>
    <description>FieldValidation</description>
    <fields>
        <fullName>AppField__c</fullName>
        <label>AppField</label>
        <referenceTo>API_Configuration__c</referenceTo>
        <relationshipLabel>FieldValidations</relationshipLabel>
        <relationshipName>FieldValidations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ValidationType__c</fullName>
        <label>ValidationType</label>
        <referenceTo>MasterValidation__c</referenceTo>
        <relationshipLabel>FieldValidations</relationshipLabel>
        <relationshipName>FieldValidations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>FieldValidation</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>FieldValidation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FieldValidations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/MasterValidation__c.object
<CustomObject>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RegexExpression__c</fullName>
        <label>RegexExpression</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ValidatorCallback__c</fullName>
        <label>ValidatorCallback</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MasterValidation</label>
    <nameField>
        <label>MasterValidation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MasterValidations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CoreValidationTest.cls
@istest
public class CoreValidationTest {
	@testsetup
    static void Setup(){
        API_Configuration__c config=new API_Configuration__c(
        	ApiName__c='LastName',
            Default_Value__c='Smith',
            FieldType__c='Text',
            isRequired__c=true,
            ObjectName__c='Contact',
            PropertyName__c='Lastname',
            ValidationMessage__c='Required field',
            Name='Patient'
        );
        MasterValidation__c masterValidation=new  MasterValidation__c(
        	Name='OnlyCharacters',
            RegexExpression__c='^[a-zA-Z]+$',
            ValidatorCallback__c='ValidationCallback.CustomRegex',
            Message__c='Only character and white spaces are allowed'
        );
        
        Insert config;
        Insert masterValidation;
        
        FieldValidation__c fldValdation=new FieldValidation__c(
        	AppField__c=config.Id,
            ValidationType__c=masterValidation.Id
        );
        Insert fldValdation;
    }
    
    testmethod static void Validation(){
        test.startTest();
        string json='{"Lastname":"Sample"}';
        CoreValidation validation=new CoreValidation();
        validation.Intialize(json,'Patient');
        validation.Validate();
        validation.ValidateJson();
        test.stopTest();
    }
    
    testmethod static void FireValidation(){
        test.startTest();
        string json='{"Lastname":""}';
        CoreValidation validation=new CoreValidation();
        validation.Intialize(json,'Patient');
        validation.ValidateJson();
        test.stopTest();
    }
    
}